# config/tasks.yaml
ad_script_task:
  description: >
    Create a radio ad script with voice direction for the product.
    Product Name: {product_name}
    Target Audience: {target_audience}
    Key Selling Points: {key_selling_points}
    Tone: {tone}
    Ad Length: {ad_length}
  expected_output: >
    List of tuples formatted as:
    [
      ("Line 1 text", "Voice direction for line 1"),
      ("Line 2 text", "Voice direction for line 2"),
      ...
    ]
  agent: ad_script_generator
  tools: []
  context: []
  inputs:
    - product_name
    - target_audience
    - key_selling_points
    - tone
    - ad_length
