# config/tasks.yaml
refine_script_task:
  description: >
    Refine the following ad script by updating ONLY the selected sentences.
    
    Original inputs:
      - Key Selling Points: {key_selling_points}
      - Tone: {tone}
      - Ad Length: {ad_length}
    
    {explicit_instruction}
    
    Current Script (with selection markers): {current_script}
    Selected Sentences (indices): {selected_sentences}
    Improvement Instruction: {improvement_instruction}
    
    RESPONSE GUIDELINES:
    1. ONLY modify the content inside [[SELECTED FOR MODIFICATION]] markers
    2. Keep ALL [[PRESERVE]] content EXACTLY as provided
    3. Return the ENTIRE script, with your modifications only to selected sentences
    4. Remove all markers ([[SELECTED FOR MODIFICATION]], [[PRESERVE]], etc.) in your final output
  expected_output: >
    List of tuples formatted as:
    [
      ("Line 1 text", "Voice direction for line 1"),
      ("Line 2 text", "Voice direction for line 2"),
      ...
    ]
  agent: refine_script_generator
  tools: []
  context: []
  inputs:
    - key_selling_points
    - tone
    - ad_length
    - current_script
    - selected_sentences
    - improvement_instruction
    - explicit_instruction
